# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d3d4dc7
_src_path: gh:scipp/copier_template
description: Imaging data reduction for the European Spallation Source
max_python: '3.13'
min_python: '3.10'
namespace_package: ess
nightly_deps: scipp,sciline,scippnexus,plopp,essreduce,scippneutron,tof
orgname: scipp
prettyname: ESSimaging
projectname: essimaging
related_projects: Scipp,Sciline,ScippNexus,Plopp,Essreduce,ScippNeutron,Tof
year: 2025
